name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: setup GOPATH dir
      run: |
        mkdir -p $HOME/go/src
        ln -s $GITHUB_WORKSPACE $HOME/go/src/
        
    - name: Build
      run: go build -v main.go 

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: main
        path: main
        
    - name: Test
      run: go test -v ./...
