name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: env
      run: env
      
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: go/src

    - name: pwd_ls
      run: |
        pwd
        ls
        ls go
        ls go/src
        
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Go env GOPATH
      run: go env GOPATH

    - name: Build
      run: |
        export GOPATH=/home/runner/work/action-test/action-test/go
        go build -v ./...

    - name: Test
      run: go test -v ./...
