name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: env
      run: env
      
    - name: Checkout code
      uses: actions/checkout@v2
      #with:
      #  path: src

    - name: pwd_ls
      run: |
        pwd
        
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: pwd_ls
      run: |
        mkdir -p /home/runner/go/src
        ln -s $GITHUB_WORKSPACE /home/runner/go/src/
        ls /home/runner/go/src
        ls /home/runner/go/src/action-test
        
    - name: Go env GOPATH
      run: go env GOPATH

    - name: Build
      run: |
        export GOPATH=GITHUB_WORKSPACE/go
        go build -v ./...

    - name: Test
      run: go test -v ./...
