# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  name: Generate Plantuml
  # You may pin to the exact commit or the version.
  # uses: grassedge/generate-plantuml-action@4936762686b831393728392054322cfde20645e8
  uses: grassedge/generate-plantuml-action@v1.5
  with:
    # path to directory which generated svg is stored
    path: # optional, default is .
    # the commit message when committing generated images
    message: # optional, default is Render PlantUML files
